/**
 * PDF generation hook using jsPDF + jspdf-autotable.
 * Generates BOL (Bill of Lading) and Invoice PDFs client-side — no server needed.
 */
import { useCallback } from 'react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { useApp } from '../context/AppContext';
import { MARKETS, formatCurrency } from '../data/markets';

function header(doc, settings, title, subTitle) {
  const mkt = MARKETS[settings.market] || MARKETS.kenya;
  // Logo box
  doc.setFillColor(37, 99, 235);
  doc.roundedRect(14, 10, 28, 18, 3, 3, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('FL', 28, 21, { align: 'center' });
  // Company name
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(14);
  doc.text(settings.companyName || 'FreightLink TMS', 47, 17);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(`${mkt.flag} ${mkt.name} · ${settings.companyEmail || ''} · ${settings.companyPhone || ''}`, 47, 23);
  // Document title (right-aligned)
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(15, 23, 42);
  doc.text(title, 196, 17, { align: 'right' });
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(subTitle, 196, 23, { align: 'right' });
  // Divider
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.5);
  doc.line(14, 32, 196, 32);
}

function footer(doc, pageNum) {
  const total = doc.internal.getNumberOfPages();
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184);
  doc.text(`Generated by FreightLink TMS · ${new Date().toLocaleDateString()} · Page ${pageNum} of ${total}`, 105, 288, { align: 'center' });
}

export function usePDF() {
  const { settings, carriers, shippers } = useApp();

  const generateBOL = useCallback((load) => {
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const mkt = MARKETS[settings.market] || MARKETS.kenya;
    const carrier = carriers.find(c => c.id === load.carrierId);
    const shipper = shippers.find(s => s.id === load.shipperId);

    header(doc, settings, 'BILL OF LADING', `BOL # ${load.id}`);

    let y = 38;

    // Route info block
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(14, y, 182, 22, 2, 2, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text(`${load.origin}`, 20, y + 8);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text('Origin', 20, y + 14);
    doc.setFontSize(14);
    doc.setTextColor(37, 99, 235);
    doc.text('→', 105, y + 10, { align: 'center' });
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text(`${load.destination}`, 190, y + 8, { align: 'right' });
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text('Destination', 190, y + 14, { align: 'right' });
    y += 28;

    // Details table
    autoTable(doc, {
      startY: y,
      head: [['Field', 'Details', 'Field', 'Details']],
      body: [
        ['Load ID',         load.id,                          'Status',         load.status],
        ['Commodity',       load.commodity,                   'Weight',         `${(load.weight||0).toLocaleString()} kg`],
        ['Truck Type',      load.truckType || '—',            'Pickup Date',    load.pickupDate || '—'],
        ['Carrier',         carrier?.name || '—',             'Delivery Date',  load.deliveryDate || '—'],
        ['Carrier Phone',   carrier?.phone || '—',            'Cargo Insurance',load.cargoInsurance ? 'Yes' : 'No'],
        ['Shipper',         shipper?.name || load.shipperContact || '—', 'Shipper Phone', load.shipperPhone || '—'],
      ],
      theme: 'grid',
      styles:       { fontSize: 9, cellPadding: 3 },
      headStyles:   { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold', fontSize: 8 },
      columnStyles: { 0: { fontStyle: 'bold', fillColor: [248, 250, 252] }, 2: { fontStyle: 'bold', fillColor: [248, 250, 252] } },
      margin: { left: 14, right: 14 },
    });

    y = doc.lastAutoTable.finalY + 8;

    // Special instructions
    if (load.specialInstructions) {
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(15, 23, 42);
      doc.text('Special Instructions:', 14, y);
      y += 5;
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(71, 85, 105);
      const lines = doc.splitTextToSize(load.specialInstructions, 168);
      doc.text(lines, 14, y);
      y += lines.length * 5 + 6;
    }

    // Timeline
    if (load.timeline?.length) {
      autoTable(doc, {
        startY: y,
        head: [['Event', 'Timestamp', 'Status']],
        body: load.timeline.map(t => [t.event, t.time || '—', t.done ? '✓ Done' : 'Pending']),
        theme: 'striped',
        styles:     { fontSize: 8, cellPadding: 2.5 },
        headStyles: { fillColor: [51, 65, 85], textColor: 255, fontStyle: 'bold' },
        margin:     { left: 14, right: 14 },
      });
      y = doc.lastAutoTable.finalY + 10;
    }

    // Signature blocks
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    ['Shipper Signature', 'Carrier Signature', 'Receiver Signature'].forEach((label, i) => {
      const x = 14 + i * 62;
      doc.setDrawColor(203, 213, 225);
      doc.line(x, y + 16, x + 54, y + 16);
      doc.text(label, x + 27, y + 21, { align: 'center' });
      doc.text('Date: _______________', x + 27, y + 27, { align: 'center' });
    });

    footer(doc, 1);
    doc.save(`BOL-${load.id}.pdf`);
  }, [settings, carriers, shippers]);

  const generateInvoice = useCallback((load) => {
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const mkt = MARKETS[settings.market] || MARKETS.kenya;
    const carrier = carriers.find(c => c.id === load.carrierId);
    const shipper = shippers.find(s => s.id === load.shipperId);
    const cur = mkt.symbol;

    header(doc, settings, 'INVOICE', `INV-${load.id}`);

    // Bill To
    let y = 38;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('BILL TO:', 14, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    doc.text(shipper?.name || load.shipperContact || 'N/A', 14, y + 5);
    doc.text(load.shipperPhone || '', 14, y + 10);

    // Invoice meta (right)
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('Invoice Date:', 130, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    doc.text(new Date().toLocaleDateString(), 175, y);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('Invoice #:', 130, y + 6);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    doc.text(`INV-${load.id}`, 175, y + 6);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('Status:', 130, y + 12);
    const statusColor = load.commissionReceived ? [5, 150, 105] : [245, 158, 11];
    doc.setTextColor(...statusColor);
    doc.setFont('helvetica', 'bold');
    doc.text(load.commissionReceived ? 'PAID' : 'OUTSTANDING', 175, y + 12);
    y += 22;

    // Line items
    const commission = load.commission || 0;
    const freight    = load.freightAmount || 0;
    const advance    = load.advance || 0;
    const net        = freight - advance;

    autoTable(doc, {
      startY: y,
      head: [['Description', 'Route', 'Amount']],
      body: [
        ['Freight Service', `${load.origin} → ${load.destination}`, `${cur} ${freight.toLocaleString()}`],
        ['Carrier Advance Paid', carrier?.name || '—', `(${cur} ${advance.toLocaleString()})`],
        ['Broker Commission', `${settings.commissionRate || 8}% of freight`, `${cur} ${commission.toLocaleString()}`],
      ],
      theme: 'grid',
      styles:     { fontSize: 9, cellPadding: 3.5 },
      headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold' },
      columnStyles: { 2: { halign: 'right', fontStyle: 'bold' } },
      margin: { left: 14, right: 14 },
    });

    y = doc.lastAutoTable.finalY + 4;

    // Totals
    const totals = [
      ['Subtotal (Freight)',   `${cur} ${freight.toLocaleString()}`],
      ['Less: Advance to Carrier', `(${cur} ${advance.toLocaleString()})`],
      ['Net Receivable',       `${cur} ${net.toLocaleString()}`],
      ['Broker Commission Due', `${cur} ${commission.toLocaleString()}`],
    ];
    totals.forEach(([label, value], i) => {
      const isLast = i === totals.length - 1;
      if (isLast) {
        doc.setFillColor(37, 99, 235);
        doc.roundedRect(110, y + 1, 86, 9, 1, 1, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFont('helvetica', 'bold');
      } else {
        doc.setTextColor(71, 85, 105);
        doc.setFont('helvetica', 'normal');
      }
      doc.setFontSize(9);
      doc.text(label, 116, y + 6.5);
      doc.text(value, 192, y + 6.5, { align: 'right' });
      y += 10;
    });

    y += 10;
    // Payment note
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text('Payment Terms: Net 30 days from invoice date', 14, y);
    doc.text(`Bank / M-Pesa / Payment details: Contact ${settings.companyEmail || 'your account manager'}`, 14, y + 5);

    footer(doc, 1);
    doc.save(`Invoice-${load.id}.pdf`);
  }, [settings, carriers, shippers]);

  return { generateBOL, generateInvoice };
}
